### ISSUE TITLE
Invalid sesskey

### ISSUE THREAD

**Issue by dcr18** [bobopinna/enrol_autoenrol#1]
I am getting an **invalid sesskey** error after adding this enrolment plugin to my courses

![inv sesskey](https://user-images.githubusercontent.com/37870003/42872736-5a0f5928-8a9b-11e8-9a4b-f5c3e6a79315.jpg)
.

Moodle: 3.5 (Build: 20180517)

AutoEnrol : 2.0 (2018022600)

**Comment by dcr18** [comment]
I have custom profile field called Class to enrol users automatically upon login.

**Comment by bobopinna** [comment]
Hello,
I'm sorry but it doesn't seem to be a bug related with autoenrol plugin.
I've tried to reproduce your problem but I never get any errors.

If you think it's still related to autoenrol plugin, please write here a step by step test guide to reproduce your problem.
